services:
  db:
    container_name: mssql
    build:
      context: ./Db
      dockerfile: Dockerfile-db
    ports:
      - "1433:1433"

  web:
    container_name: web
    build:
      context: ./SuperHeroAPI-DotNet8
      dockerfile: Dockerfile-web
    depends_on:
      - db
    ports:
      - "0.0.0.0:8080:8080"